[pytest]
testpaths = tests

# Show shorter, cleaner tracebacks
addopts = -ra -q

# Filter out 3rd-party warnings (from rembg)
filterwarnings =
    ignore:'mode' parameter is deprecated:DeprecationWarning
    ignore:.*distutils.*:DeprecationWarning
    ignore:.*np.bool8.*:DeprecationWarning

# Optional: markers (for organizing)
markers =
    preprocessing: Tests for preprocessing.py
    solver: Tests for solver.py